version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Installing Django"
      - pip install django
  build:
    commands:
      - echo "Running migrations"
      - python manage.py makemigrations
      - python manage.py migrate
      - echo "Creating superuser"
      - python manage.py createsuperuser --noinput --username=admin --email=ambrosh.lade@gmail.com
  post_build:
    commands:
      - echo "Build completed successfully"
artifacts:
  files:
    - '**/*'
  discard-paths: yes
