version: 0.2

phases:
  install:
    runtime-versions:
      python: 3
    commands:
      - echo Installing dependencies
      - pip install awscli
      
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 905418111557.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-django-app .

  post_build:
    commands:
      - echo Tagging Docker image...
      - docker tag my-django-app:latest 905418111557.dkr.ecr.ap-south-1.amazonaws.com/practice:latest
      - echo Pushing Docker image to Amazon ECR...
      - docker push 905418111557.dkr.ecr.ap-south-1.amazonaws.com/practice:latest
