version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12

  pre_build:
    commands:
      # Install Docker
      - apt-get update
      - apt-get install -y docker.io

  build:
    commands:
      # Build Docker image
      - docker build -t 905418111557.dkr.ecr.ap-south-1.amazonaws.com/todo-list .

  post_build:
    commands:
      # Login to ECR
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 905418111557.dkr.ecr.ap-south-1.amazonaws.com
      # Push Docker image to ECR
      - docker push 905418111557.dkr.ecr.ap-south-1.amazonaws.com/todo-list
