version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 905418111557.dkr.ecr.ap-south-1.amazonaws.com
      
  build:
    commands:
      - echo Build started on $(date)
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI

  post_build:
    commands:
      - echo Tagging Docker image...
      - docker tag $REPOSITORY_URI:latest 905418111557.dkr.ecr.ap-south-1.amazonaws.com/practice:latest
      - echo Pushing Docker image to Amazon ECR...
      - docker push 905418111557.dkr.ecr.ap-south-1.amazonaws.com/practice:latest
      - echo Running Docker container...
      - docker run --name my-django-container -p 8000:8000 -d 905418111557.dkr.ecr.ap-south-1.amazonaws.com/practice:latest
