apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-list
  template:
    metadata:
      labels:
        app: todo-list
    spec:
      containers:
      - name: todo-list-container
        image: public.ecr.aws/l6s9i6b7/todo-list:latest
        ports:
        - containerPort: 8000
